\c uudex

INSERT INTO "privilege_allowed" VALUES (1, 'BROADEST_ALLOWED_PUBLISHER_ACCESS');
INSERT INTO "privilege_allowed" VALUES (2, 'BROADEST_ALLOWED_SUBSCRIBER_ACCESS');
INSERT INTO "privilege_allowed" VALUES (3, 'BROADEST_ALLOWED_MANAGER_ACCESS');
