#!/usr/bin/env python3
"""
File Concatenation Tool for Model Training

This script concatenates Python source files into a single output file while preserving
module structure information. It's particularly useful for preparing source code for
model training or analysis purposes.

The tool provides multiple ways to specify input files:
    - Individual files using --file (can be specified multiple times)
    - Directory scanning using --dir (recursive)
    - File list using --file-list (YAML format)

The output includes module path information derived from the source file structure,
making it easy to understand the original code organization.

Example Usage:
    # Using individual files
    python scoop-files-for-model.py --file src/module1.py --file src/module2.py --output-file output.txt --root myproject

    # Using a directory
    python scoop-files-for-model.py --dir ./src --output-file output.txt --root myproject

    # Using a YAML file list
    python scoop-files-for-model.py --file-list files.yml --output-file output.txt --root myproject

YAML file format example (files.yml):
    - src/module1.py
    - src/package1/module2.py
    - src/package1/subpackage/module3.py

Output Format:
    # Combined Python files from root module: myproject
    # Generated by scoop-files-for-model.py

    # Module: myproject.module1
    #===============================================================================
    [contents of module1.py]

    # Module: myproject.package1.module2
    #===============================================================================
    [contents of module2.py]
"""

import argparse
import os
import sys
import yaml
from typing import List, Set


def collect_python_files(files: List[str], directory: str,
                         file_list: str) -> Set[str]:
    """
    Collect Python files from various input sources.

    Args:
        files: List of individual Python files
        directory: Directory to scan for Python files
        file_list: YAML file containing list of Python files

    Returns:
        Set of absolute paths to Python files
    """
    python_files = set()

    # Process individual files
    if files:
        for file in files:
            if os.path.exists(file) and file.endswith('.py'):
                python_files.add(os.path.abspath(file))
            else:
                print(
                    f"Warning: File {file} does not exist or is not a Python file",
                    file=sys.stderr)

    # Process directory
    if directory:
        if os.path.isdir(directory):
            for root, _, files in os.walk(directory):
                for file in files:
                    if file.endswith('.py'):
                        python_files.add(
                            os.path.abspath(os.path.join(root, file)))
        else:
            print(f"Warning: Directory {directory} does not exist",
                  file=sys.stderr)

    # Process file list from YAML
    if file_list:
        if os.path.exists(file_list):
            try:
                with open(file_list, 'r') as f:
                    yaml_content = yaml.safe_load(f)
                    if isinstance(yaml_content, list):
                        for file in yaml_content:
                            if os.path.exists(file) and file.endswith('.py'):
                                python_files.add(os.path.abspath(file))
                            else:
                                print(
                                    f"Warning: File {file} from YAML does not exist or is not a Python file",
                                    file=sys.stderr)
                    else:
                        print(
                            f"Warning: YAML file {file_list} should contain a list of files",
                            file=sys.stderr)
            except yaml.YAMLError as e:
                print(f"Error reading YAML file {file_list}: {e}",
                      file=sys.stderr)
        else:
            print(f"Warning: YAML file {file_list} does not exist",
                  file=sys.stderr)

    return python_files


def extract_file_header(content: str) -> tuple[str, str]:
    """
    Extract the file header (special comments at the start of the file) from the content.

    Args:
        content: The file content

    Returns:
        Tuple of (header, remaining_content)
    """
    lines = content.split('\n')
    header_lines = []
    content_lines = []

    # Process lines until we find non-comment content
    in_header = True
    for line in lines:
        stripped = line.strip()
        # Check for common file headers and full-line comments
        if in_header and (stripped.startswith('#')
                          or stripped.startswith('"""')
                          or stripped.startswith("'''") or stripped == ''):
            # Special handling for vim/emacs modelines and encoding declarations
            if ('vim:' in stripped or 'coding:' in stripped
                    or '-*-' in stripped or 'emacs' in stripped
                    or '{{{' in stripped or '}}}' in stripped):
                header_lines.append(line)
            # Skip other full-line comments in header
            continue
        else:
            in_header = False
            content_lines.append(line)

    return '\n'.join(header_lines), '\n'.join(content_lines)


def clean_content(content: str) -> str:
    """
    Clean the file content by removing full-line comments while preserving
    inline comments and docstrings.

    Args:
        content: The file content

    Returns:
        Cleaned content
    """
    lines = content.split('\n')
    cleaned_lines = []
    in_multiline = False
    multiline_delimiter = None

    for line in lines:
        stripped = line.strip()

        # Handle multiline strings (docstrings)
        if not in_multiline:
            if stripped.startswith('"""'):
                in_multiline = True
                multiline_delimiter = '"""'
                cleaned_lines.append(line)
                continue
            elif stripped.startswith("'''"):
                in_multiline = True
                multiline_delimiter = "'''"
                cleaned_lines.append(line)
                continue
        else:
            cleaned_lines.append(line)
            if multiline_delimiter and multiline_delimiter in stripped:
                in_multiline = False
            continue

        # Skip full-line comments but keep inline comments and non-comments
        if not stripped.startswith('#'):
            cleaned_lines.append(line)

    return '\n'.join(cleaned_lines)


def get_module_path(file_path: str, root_module: str) -> str:
    """
    Convert a file path to a module path based on the root module.

    Args:
        file_path: Absolute path to the Python file
        root_module: Root module name

    Returns:
        Module path (e.g., volttron.messagebus.zmq)
    """
    # Get the relative path and remove .py extension
    rel_path = os.path.relpath(file_path)
    if rel_path.endswith('.py'):
        rel_path = rel_path[:-3]

    # Convert path separators to dots and handle src directory
    parts = rel_path.split(os.sep)
    if 'src' in parts:
        # Find everything after 'src' in the path
        src_index = parts.index('src')
        module_parts = parts[src_index + 1:]
    else:
        module_parts = parts

    # If the file is __init__.py, remove the last part
    if module_parts[-1] == '__init__':
        module_parts = module_parts[:-1]

    return '.'.join(module_parts)


def concatenate_files(files: Set[str], output_file: str,
                      root_module: str) -> None:
    """
    Concatenate Python files into a single output file.

    Args:
        files: Set of Python files to concatenate
        output_file: Output file path
        root_module: Root module name
    """
    all_headers = []

    with open(output_file, 'w') as out:
        # First pass: collect all headers
        for file in sorted(files):
            try:
                with open(file, 'r') as f:
                    content = f.read()
                header, _ = extract_file_header(content)
                if header:
                    all_headers.append(header)
            except Exception as e:
                print(f"Error processing header from {file}: {e}",
                      file=sys.stderr)

        # Write combined header
        if all_headers:
            out.write("# Combined file headers\n")
            out.write("#" + "=" * 79 + "\n")
            for header in all_headers:
                out.write(header + "\n")
            out.write("#" + "=" * 79 + "\n\n")

        # Write tool header
        out.write(f"# Combined Python files from root module: {root_module}\n")
        out.write("# Generated by scoop-files-for-model.py\n\n")

        # Second pass: process and write file contents
        for file in sorted(files):
            try:
                with open(file, 'r') as f:
                    content = f.read()

                # Extract header and clean content
                _, content = extract_file_header(content)
                cleaned_content = clean_content(content)

                if cleaned_content.strip(
                ):  # Only write if there's content after cleaning
                    module_path = get_module_path(file, root_module)
                    out.write(f"\n# Module: {module_path}\n")
                    out.write("#" + "=" * 79 + "\n\n")
                    out.write(cleaned_content.strip())
                    out.write("\n\n")
            except Exception as e:
                print(f"Error processing file {file}: {e}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description=
        "Concatenate Python files from various sources into a single file with module path information.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Concatenate specific Python files
  %(prog)s --file src/module1.py --file src/module2.py --output-file output.txt --root myproject

  # Concatenate all Python files from a directory
  %(prog)s --dir ./src --output-file output.txt --root myproject

  # Concatenate files listed in a YAML file
  %(prog)s --file-list files.yml --output-file output.txt --root myproject

YAML file format (files.yml):
  - src/module1.py
  - src/package1/module2.py
  - src/package1/subpackage/module3.py
""")

    input_group = parser.add_argument_group('Input Options')
    input_group.add_argument(
        '--file',
        action='append',
        metavar='FILE',
        help=
        'Python file to include. This option can be specified multiple times to include several files'
    )
    input_group.add_argument(
        '--dir',
        metavar='DIR',
        help=
        'Directory to recursively scan for Python files. All .py files under this directory will be included'
    )
    input_group.add_argument(
        '--file-list',
        metavar='YAML_FILE',
        help=
        'YAML file containing a list of Python files to include. Each entry should be a path to a .py file'
    )

    output_group = parser.add_argument_group('Output Options')
    output_group.add_argument(
        '--output-file',
        required=True,
        metavar='FILE',
        help='Path to the output file where concatenated code will be written')
    output_group.add_argument(
        '--root',
        required=True,
        metavar='MODULE',
        help='Root module name used for generating module paths in the output')

    args = parser.parse_args()

    if not (args.file or args.dir or args.file_list):
        parser.error(
            "At least one input source (--file, --dir, or --file-list) must be specified"
        )

    # Collect all Python files
    python_files = collect_python_files(args.file, args.dir, args.file_list)

    if not python_files:
        print("No Python files found to process", file=sys.stderr)
        sys.exit(1)

    # Concatenate files
    concatenate_files(python_files, args.output_file, args.root)
    print(
        f"Successfully concatenated {len(python_files)} files to {args.output_file}"
    )


if __name__ == '__main__':
    main()
