version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/.docker-conf/postgresql_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
      #extra_hosts:
      #- "host.docker.internal:172.20.128.1"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - "RABBITMQ_DEFAULT_USER=uudex"
      - "RABBITMQ_DEFAULT_PASS=uudex"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    #extra_hosts:
    #  - "host.docker.internal:172.20.128.1"
