# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from api.participant_api import ParticipantApi  # noqa: E501
from uudex_client.rest import ApiException


class TestParticipantApi(unittest.TestCase):
    """ParticipantApi unit test stubs"""

    def setUp(self):
        self.api = api.participant_api.ParticipantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_create_participant(self):
        """Test case for auth_create_participant

        Create a single Participant  # noqa: E501
        """
        pass

    def test_auth_create_participant_contact(self):
        """Test case for auth_create_participant_contact

        Create a single Participant Contact  # noqa: E501
        """
        pass

    def test_auth_delete_participant(self):
        """Test case for auth_delete_participant

        Delete a single Participant  # noqa: E501
        """
        pass

    def test_auth_delete_participant_contact(self):
        """Test case for auth_delete_participant_contact

        Delete a single Contact for the Participant  # noqa: E501
        """
        pass

    def test_auth_get_all_participant_contacts(self):
        """Test case for auth_get_all_participant_contacts

        Return a collection of all Contacts for given Participant  # noqa: E501
        """
        pass

    def test_auth_get_all_participant_groups(self):
        """Test case for auth_get_all_participant_groups

        Returns a collection of groups the Participant is a member of  # noqa: E501
        """
        pass

    def test_auth_get_all_participants(self):
        """Test case for auth_get_all_participants

        Return a collection of all Participants in the system  # noqa: E501
        """
        pass

    def test_auth_get_participant(self):
        """Test case for auth_get_participant

        Get a single Participant  # noqa: E501
        """
        pass

    def test_auth_get_participant_contact(self):
        """Test case for auth_get_participant_contact

        Get a single Contact for the Participant  # noqa: E501
        """
        pass

    def test_auth_update_participant(self):
        """Test case for auth_update_participant

        Update a single Participant  # noqa: E501
        """
        pass

    def test_auth_update_participant_contact(self):
        """Test case for auth_update_participant_contact

        Update a single Contact for the Participant  # noqa: E501
        """
        pass

    def test_get_parent_participant(self):
        """Test case for get_parent_participant

        Returns the calling Endpoint's parent Participant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
