# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from models.endpoint_uuid import EndpointUuid  # noqa: E501
from uudex_client.rest import ApiException


class TestEndpointUuid(unittest.TestCase):
    """EndpointUuid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointUuid(self):
        """Test EndpointUuid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uudex_client.models.endpoint_uuid.EndpointUuid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
