# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from models.subject_enriched import SubjectEnriched  # noqa: E501
from uudex_client.rest import ApiException


class TestSubjectEnriched(unittest.TestCase):
    """SubjectEnriched unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubjectEnriched(self):
        """Test SubjectEnriched"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uudex_client.models.subject_enriched.SubjectEnriched()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
