# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from api.role_api import RoleApi  # noqa: E501
from uudex_client.rest import ApiException


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = api.role_api.RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_create_role(self):
        """Test case for auth_create_role

        Create a single Role  # noqa: E501
        """
        pass

    def test_auth_delete_role(self):
        """Test case for auth_delete_role

        Delete a single Role  # noqa: E501
        """
        pass

    def test_auth_get_all_roles(self):
        """Test case for auth_get_all_roles

        Return a collection of all Roles in the system  # noqa: E501
        """
        pass

    def test_auth_get_role(self):
        """Test case for auth_get_role

        Get a single Role  # noqa: E501
        """
        pass

    def test_auth_get_role_endpoints(self):
        """Test case for auth_get_role_endpoints

        Returns all Endpoints that have been granted the given Role  # noqa: E501
        """
        pass

    def test_auth_grant_role(self):
        """Test case for auth_grant_role

        Grant role to the given Endpoint  # noqa: E501
        """
        pass

    def test_auth_update_role(self):
        """Test case for auth_update_role

        Update a single Role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
