# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from models.subscription_enriched_subjects import SubscriptionEnrichedSubjects  # noqa: E501
from uudex_client.rest import ApiException


class TestSubscriptionEnrichedSubjects(unittest.TestCase):
    """SubscriptionEnrichedSubjects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionEnrichedSubjects(self):
        """Test SubscriptionEnrichedSubjects"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uudex_client.models.subscription_enriched_subjects.SubscriptionEnrichedSubjects()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
