# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from models.metadata_change_log import MetadataChangeLog  # noqa: E501
from uudex_client.rest import ApiException


class TestMetadataChangeLog(unittest.TestCase):
    """MetadataChangeLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataChangeLog(self):
        """Test MetadataChangeLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uudex_client.models.metadata_change_log.MetadataChangeLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
