# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from api.group_api import GroupApi  # noqa: E501
from uudex_client.rest import ApiException


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self):
        self.api = api.group_api.GroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_add_group_manager(self):
        """Test case for auth_add_group_manager

        Adds a Group Manager to a Group  # noqa: E501
        """
        pass

    def test_auth_add_group_member(self):
        """Test case for auth_add_group_member

        Add a member to a group  # noqa: E501
        """
        pass

    def test_auth_create_group(self):
        """Test case for auth_create_group

        Create a single Group  # noqa: E501
        """
        pass

    def test_auth_delete_group(self):
        """Test case for auth_delete_group

        Delete a single Group  # noqa: E501
        """
        pass

    def test_auth_get_all_group_managers(self):
        """Test case for auth_get_all_group_managers

        Return a collection of Group Managers for the given Group  # noqa: E501
        """
        pass

    def test_auth_get_all_group_members(self):
        """Test case for auth_get_all_group_members

        Return a collection of Group Members for the given Group  # noqa: E501
        """
        pass

    def test_auth_get_all_groups(self):
        """Test case for auth_get_all_groups

        Return a collection of all Groups the invoker has manage rights to  # noqa: E501
        """
        pass

    def test_auth_get_group(self):
        """Test case for auth_get_group

        Get a single Group  # noqa: E501
        """
        pass

    def test_auth_remove_group_manager(self):
        """Test case for auth_remove_group_manager

        Remove a Group Manager from a Group  # noqa: E501
        """
        pass

    def test_auth_remove_group_member(self):
        """Test case for auth_remove_group_member

        Remove a member from a Group  # noqa: E501
        """
        pass

    def test_auth_update_group(self):
        """Test case for auth_update_group

        Update a single Group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
