# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from api.subject_api import SubjectApi  # noqa: E501
from uudex_client.rest import ApiException


class TestSubjectApi(unittest.TestCase):
    """SubjectApi unit test stubs"""

    def setUp(self):
        self.api = api.subject_api.SubjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_subject(self):
        """Test case for create_subject

        Creates a Subject if the calling participant is authorized  # noqa: E501
        """
        pass

    def test_delete_subject(self):
        """Test case for delete_subject

        Delete a single Subject the invoker is authorized to use  # noqa: E501
        """
        pass

    def test_discover_subjects(self):
        """Test case for discover_subjects

        Returns a collection of Subjects the calling endpoint is authorized to view.  Optionally filter by subject name.  # noqa: E501
        """
        pass

    def test_get_subject(self):
        """Test case for get_subject

        Get a single Subject the invoker is authorized to use  # noqa: E501
        """
        pass

    def test_get_subjects(self):
        """Test case for get_subjects

        Return a collection of Subjects  # noqa: E501
        """
        pass

    def test_publish_message(self):
        """Test case for publish_message

        Publishes one or more messages  # noqa: E501
        """
        pass

    def test_update_subject(self):
        """Test case for update_subject

        Update a single Subject the invoker is authorized to use  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
