# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from models.endpoint import Endpoint  # noqa: E501
from uudex_client.rest import ApiException


class TestEndpoint(unittest.TestCase):
    """Endpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpoint(self):
        """Test Endpoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uudex_client.models.endpoint.Endpoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
