# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uudex_client
from models.generic_auth_object import GenericAuthObject  # noqa: E501
from uudex_client.rest import ApiException


class TestGenericAuthObject(unittest.TestCase):
    """GenericAuthObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericAuthObject(self):
        """Test GenericAuthObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uudex_client.models.generic_auth_object.GenericAuthObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
