# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Contact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contact_id': 'int',
        'contact_name': 'str',
        'contact_number': 'str',
        'participant_uuid': 'str'
    }

    attribute_map = {
        'contact_id': 'contact_id',
        'contact_name': 'contact_name',
        'contact_number': 'contact_number',
        'participant_uuid': 'participant_uuid'
    }

    def __init__(self, contact_id=None, contact_name=None, contact_number=None, participant_uuid=None):  # noqa: E501
        """Contact - a model defined in Swagger"""  # noqa: E501
        self._contact_id = None
        self._contact_name = None
        self._contact_number = None
        self._participant_uuid = None
        self.discriminator = None
        if contact_id is not None:
            self.contact_id = contact_id
        self.contact_name = contact_name
        self.contact_number = contact_number
        self.participant_uuid = participant_uuid

    @property
    def contact_id(self):
        """Gets the contact_id of this Contact.  # noqa: E501


        :return: The contact_id of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._contact_id

    @contact_id.setter
    def contact_id(self, contact_id):
        """Sets the contact_id of this Contact.


        :param contact_id: The contact_id of this Contact.  # noqa: E501
        :type: int
        """

        self._contact_id = contact_id

    @property
    def contact_name(self):
        """Gets the contact_name of this Contact.  # noqa: E501


        :return: The contact_name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._contact_name

    @contact_name.setter
    def contact_name(self, contact_name):
        """Sets the contact_name of this Contact.


        :param contact_name: The contact_name of this Contact.  # noqa: E501
        :type: str
        """
        if contact_name is None:
            raise ValueError("Invalid value for `contact_name`, must not be `None`")  # noqa: E501

        self._contact_name = contact_name

    @property
    def contact_number(self):
        """Gets the contact_number of this Contact.  # noqa: E501


        :return: The contact_number of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._contact_number

    @contact_number.setter
    def contact_number(self, contact_number):
        """Sets the contact_number of this Contact.


        :param contact_number: The contact_number of this Contact.  # noqa: E501
        :type: str
        """
        if contact_number is None:
            raise ValueError("Invalid value for `contact_number`, must not be `None`")  # noqa: E501

        self._contact_number = contact_number

    @property
    def participant_uuid(self):
        """Gets the participant_uuid of this Contact.  # noqa: E501


        :return: The participant_uuid of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._participant_uuid

    @participant_uuid.setter
    def participant_uuid(self, participant_uuid):
        """Sets the participant_uuid of this Contact.


        :param participant_uuid: The participant_uuid of this Contact.  # noqa: E501
        :type: str
        """
        if participant_uuid is None:
            raise ValueError("Invalid value for `participant_uuid`, must not be `None`")  # noqa: E501

        self._participant_uuid = participant_uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Contact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
