# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Group(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'igroup_uuid': 'str',
        'group_name': 'str',
        'description': 'str'
    }

    attribute_map = {
        'igroup_uuid': 'igroup_uuid',
        'group_name': 'group_name',
        'description': 'description'
    }

    def __init__(self, igroup_uuid=None, group_name=None, description=None):  # noqa: E501
        """Group - a model defined in Swagger"""  # noqa: E501
        self._igroup_uuid = None
        self._group_name = None
        self._description = None
        self.discriminator = None
        if igroup_uuid is not None:
            self.igroup_uuid = igroup_uuid
        self.group_name = group_name
        self.description = description

    @property
    def igroup_uuid(self):
        """Gets the igroup_uuid of this Group.  # noqa: E501


        :return: The igroup_uuid of this Group.  # noqa: E501
        :rtype: str
        """
        return self._igroup_uuid

    @igroup_uuid.setter
    def igroup_uuid(self, igroup_uuid):
        """Sets the igroup_uuid of this Group.


        :param igroup_uuid: The igroup_uuid of this Group.  # noqa: E501
        :type: str
        """

        self._igroup_uuid = igroup_uuid

    @property
    def group_name(self):
        """Gets the group_name of this Group.  # noqa: E501


        :return: The group_name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this Group.


        :param group_name: The group_name of this Group.  # noqa: E501
        :type: str
        """
        if group_name is None:
            raise ValueError("Invalid value for `group_name`, must not be `None`")  # noqa: E501

        self._group_name = group_name

    @property
    def description(self):
        """Gets the description of this Group.  # noqa: E501


        :return: The description of this Group.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Group.


        :param description: The description of this Group.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Group, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
