# coding: utf-8

"""
    UUDEXApi

    uudex api  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jeff.welsh@pnnl.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from uudex_client.models import Participant


class ParticipantEnriched(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'participant_uuid': 'str',
        'participant_short_name': 'str',
        'participant_long_name': 'str',
        'description': 'str',
        'active_sw': 'str',
        'create_datetime': 'datetime',
        'contacts': 'list[Contact]'
    }
    if hasattr(Participant, "swagger_types"):
        swagger_types.update(Participant.swagger_types)

    attribute_map = {
        'participant_uuid': 'participant_uuid',
        'participant_short_name': 'participant_short_name',
        'participant_long_name': 'participant_long_name',
        'description': 'description',
        'active_sw': 'active_sw',
        'create_datetime': 'create_datetime',
        'contacts': 'contacts'
    }
    if hasattr(Participant, "attribute_map"):
        attribute_map.update(Participant.attribute_map)

    def __init__(self, participant_uuid=None, participant_short_name=None, participant_long_name=None, description=None, active_sw=None, create_datetime=None, contacts=None, *args, **kwargs):  # noqa: E501
        """ParticipantEnriched - a model defined in Swagger"""  # noqa: E501
        self._participant_uuid = None
        self._participant_short_name = None
        self._participant_long_name = None
        self._description = None
        self._active_sw = None
        self._create_datetime = None
        self._contacts = None
        self.discriminator = None
        if participant_uuid is not None:
            self.participant_uuid = participant_uuid
        self.participant_short_name = participant_short_name
        self.participant_long_name = participant_long_name
        self.description = description
        self.active_sw = active_sw
        if create_datetime is not None:
            self.create_datetime = create_datetime
        self.contacts = contacts
        # Participant.__init__(self, *args, **kwargs)

    @property
    def participant_uuid(self):
        """Gets the participant_uuid of this ParticipantEnriched.  # noqa: E501


        :return: The participant_uuid of this ParticipantEnriched.  # noqa: E501
        :rtype: str
        """
        return self._participant_uuid

    @participant_uuid.setter
    def participant_uuid(self, participant_uuid):
        """Sets the participant_uuid of this ParticipantEnriched.


        :param participant_uuid: The participant_uuid of this ParticipantEnriched.  # noqa: E501
        :type: str
        """

        self._participant_uuid = participant_uuid

    @property
    def participant_short_name(self):
        """Gets the participant_short_name of this ParticipantEnriched.  # noqa: E501


        :return: The participant_short_name of this ParticipantEnriched.  # noqa: E501
        :rtype: str
        """
        return self._participant_short_name

    @participant_short_name.setter
    def participant_short_name(self, participant_short_name):
        """Sets the participant_short_name of this ParticipantEnriched.


        :param participant_short_name: The participant_short_name of this ParticipantEnriched.  # noqa: E501
        :type: str
        """
        if participant_short_name is None:
            raise ValueError("Invalid value for `participant_short_name`, must not be `None`")  # noqa: E501

        self._participant_short_name = participant_short_name

    @property
    def participant_long_name(self):
        """Gets the participant_long_name of this ParticipantEnriched.  # noqa: E501


        :return: The participant_long_name of this ParticipantEnriched.  # noqa: E501
        :rtype: str
        """
        return self._participant_long_name

    @participant_long_name.setter
    def participant_long_name(self, participant_long_name):
        """Sets the participant_long_name of this ParticipantEnriched.


        :param participant_long_name: The participant_long_name of this ParticipantEnriched.  # noqa: E501
        :type: str
        """
        if participant_long_name is None:
            raise ValueError("Invalid value for `participant_long_name`, must not be `None`")  # noqa: E501

        self._participant_long_name = participant_long_name

    @property
    def description(self):
        """Gets the description of this ParticipantEnriched.  # noqa: E501


        :return: The description of this ParticipantEnriched.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ParticipantEnriched.


        :param description: The description of this ParticipantEnriched.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def active_sw(self):
        """Gets the active_sw of this ParticipantEnriched.  # noqa: E501


        :return: The active_sw of this ParticipantEnriched.  # noqa: E501
        :rtype: str
        """
        return self._active_sw

    @active_sw.setter
    def active_sw(self, active_sw):
        """Sets the active_sw of this ParticipantEnriched.


        :param active_sw: The active_sw of this ParticipantEnriched.  # noqa: E501
        :type: str
        """
        if active_sw is None:
            raise ValueError("Invalid value for `active_sw`, must not be `None`")  # noqa: E501
        allowed_values = ["Y", "N"]  # noqa: E501
        if active_sw not in allowed_values:
            raise ValueError(
                "Invalid value for `active_sw` ({0}), must be one of {1}"  # noqa: E501
                .format(active_sw, allowed_values)
            )

        self._active_sw = active_sw

    @property
    def create_datetime(self):
        """Gets the create_datetime of this ParticipantEnriched.  # noqa: E501


        :return: The create_datetime of this ParticipantEnriched.  # noqa: E501
        :rtype: datetime
        """
        return self._create_datetime

    @create_datetime.setter
    def create_datetime(self, create_datetime):
        """Sets the create_datetime of this ParticipantEnriched.


        :param create_datetime: The create_datetime of this ParticipantEnriched.  # noqa: E501
        :type: datetime
        """

        self._create_datetime = create_datetime

    @property
    def contacts(self):
        """Gets the contacts of this ParticipantEnriched.  # noqa: E501


        :return: The contacts of this ParticipantEnriched.  # noqa: E501
        :rtype: list[Contact]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this ParticipantEnriched.


        :param contacts: The contacts of this ParticipantEnriched.  # noqa: E501
        :type: list[Contact]
        """
        if contacts is None:
            raise ValueError("Invalid value for `contacts`, must not be `None`")  # noqa: E501

        self._contacts = contacts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ParticipantEnriched, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParticipantEnriched):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
